- name: Run ML Pipeline
  run: |
    python src/pipeline.py

- name: Run Tests
  run: |
    pytest

- name: Upload Model
  uses: actions/upload-artifact@v4
  with:
    name: trained-model
    path: model/model.pkl

- name: Upload MLflow Logs
  uses: actions/upload-artifact@v4
  with:
    name: mlflow-runs
    path: mlruns/ 
